//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChiTieu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterMoneyEntities1 : DbContext
    {
        public MasterMoneyEntities1()
            : base("name=MasterMoneyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MyCategory> MyCategories { get; set; }
        public virtual DbSet<MyWallet> MyWallets { get; set; }
        public virtual DbSet<MyTransfer> MyTransfers { get; set; }
    }
}
