//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChiTieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTransfer
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public Nullable<int> IdWallet { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string Note { get; set; }
    }
}
